name: Build and Test

on:
  push:
    branches:
    - main
    - releases/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          environment-app-key: ${{secrets.UPDRAFT_ENV_APP_KEY}}
          api-key: ${{secrets.UPDRAFT_API_KEY}}
          app: ./samples/sample.apk
