name: Build and Test

on:
  push:
    branches:
    - main
    - releases/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          ENVIRONMENT_APP_KEY: ${{secrets.UPDRAFT_ENV_KEY}}
          API_KEY: ${{secrets.UPDRAFT_API_KEY}}
          APP: ./samples/sample.apk
